#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Sun Feb  8 01:16:34 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class tiff_generator(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: tiff_generator.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.textCtrl1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.checkbox1 = wx.CheckBox(self, wx.ID_ANY, _("checkbox_1"))
        self.button = wx.Button(self, wx.ID_ANY, _("button_1"))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: tiff_generator.__set_properties
        self.SetTitle(_("Tiff Generator"))
        self.SetSize((528, 373))
        self.panel_1.SetMinSize((528, 288))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: tiff_generator.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.textCtrl1, 0, 0, 0)
        sizer_1.Add(self.checkbox1, 0, 0, 0)
        sizer_1.Add(self.button, 0, 0, 0)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class tiff_generator
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    tiff_generator = tiff_generator(None, wx.ID_ANY, "")
    app.SetTopWindow(tiff_generator)
    tiff_generator.Show()
    app.MainLoop()